
<?php
$names=['adarsh','pramod','prasid','prasiddha','prasiddhi'];

foreach ($names as $key => $n) {
   echo $key. ":";
   echo $n . "\n";
   # code...
}

# NOTE:
        # Array will start from 0
        # So when key is given the numbers are autogenerated from zero



# Without key

foreach ($names as $f){
        echo $f . "\n";
    }